### ISSUE TITLE
App Grid Gap

### ISSUE THREAD

**Issue by jJit0** [Selenium-H/App-Grid-Tweaks#11] opened 2021-10-28 12:09 UTC
Hi,

I noticed that when I configure the grid 6Rx11C, the corner gaps are small, which expands the icons to the whole screen, as you see below:
[https://i.imgur.com/rkw7cyp.png](url)

But when I switch to 6Rx12C, the corner gaps are big, which narrows the space between icons
[https://i.imgur.com/UUlkX2D.png](url)

Do you have an explanation to this ?

By the way, I'm using Gnome 41.0 nad other Gnome Extensions like Just-Perfection and Dash-to-Panel

**Comment by Selenium-H** [comment] 2021-11-21 19:28
Hi @jJit0, Unfortunately, I'm not sure what's causing this issue. From `GNOME 40` there are padding on the sides beyond which the app grid can''t extend even though the `row-spacing` and `column-spacing` is changed in through extension. This is probably dependent on the resolution of the screen and aspect ratio.

**Comment by jJit0** [comment] 2021-11-21 19:32
I'm on Gnome 41 now, and the issue is still here.

I have a 1080p laptop screen and I also use a 1080p 21" inch monitor

The external monitor is ok, even after refreshing X server `Alt+F2 -> r` 
But when I am on my laptop's screen, when I do `Alt+F2 -> r` , all icons are piled up

**Comment by Selenium-H** [comment] 2021-11-22 13:26
Thanks for the information. Currently working on a workaround. I'll update once done.

**Comment by jJit0** [comment] 2021-11-22 13:29
Once updated, I'll be your first tester.

Will keep updated

**Comment by Selenium-H** [comment] 2021-11-23 08:06
Please try the latest version from [experimental](https://github.com/Selenium-H/App-Grid-Tweaks/tree/experimental) `branch`. 

The new `Minimum side padding for App Grid [in px]` option reduces the side padding which can be manually set.
![Image_03](https://user-images.githubusercontent.com/46006930/142988642-6c117c11-d75d-44be-808a-22e3fe6fa23e.png)
Also, please set the `App Icon size` accordingly.

**Comment by jJit0** [comment] 2021-11-23 14:07
Ok, so I have tested it, and the result is very buggy.

I set those setttings as you can see here: https://i.imgur.com/Ai1xTCg.png

And here is what I got when I refreshed X `Alt+F2 -> r` https://i.imgur.com/NpNZqx0.png

I've also decreased and increased `App Icon Size` and `Minimum Size Padding` values but nothing changed

Sure, it looks much better with padding, but 3 App rows are gone and moved into another page

**Comment by Selenium-H** [comment] 2021-11-26 21:59
Thanks for the update. I think this is happening due to the customization of positions of app icons before enabling the extension. The position of all app icons are saved once an icon is dragged.  Please try the following -
Disable the extension.
In `dconf Editor`, set  `org/gnome/shell/app-picker-layout` to default. Note that this will rearrange the positions of all app icons in alphabetical order.
Restart `GNOME Shell` and enable the extension again and check if the issue persists.

**Comment by jJit0** [comment] 2021-11-26 22:03
It is by default, look:
`gsettings get org.gnome.shell app-picker-layout`
`@aa{sv} []`

**Comment by jJit0** [comment] 2021-11-26 22:22
If you want to test it yourself with my customization, you have to install both `Dash-to-Panel` and `Just-Perfection` extensions
- For Dash-to-Panel, do this: https://i.imgur.com/7McPsEd.png
- For Just-Perfection, follow all my settings:
https://i.imgur.com/SbpmLEj.png
https://i.imgur.com/itEUUL5.png
https://i.imgur.com/yQitu5h.png
https://i.imgur.com/q3zTlw4.png

**Comment by Selenium-H** [comment] 2021-11-26 23:02
Thanks for the update. I was able to reproduce the issue. I'll update one an workaround can be found..

**Comment by Selenium-H** [comment] 2021-11-28 22:46
Please try the latest version from [experimental](https://github.com/Selenium-H/App-Grid-Tweaks/tree/experimental) `branch`.

**Comment by jJit0** [comment] 2021-11-29 13:11
YESSSSS XD

It's working greattttt :-)

Here is what I did:
- https://i.imgur.com/oKAVbmZ.png 
- https://i.imgur.com/TLGsFIA.png

I think you should merge this branch to the master one, what do you think ?

**Comment by Selenium-H** [comment] 2021-11-30 00:39
Thanks for the update.
Yes, its merged now.

**Closed by Selenium-H** 2021-11-30 00:39 UTC
